# Generated by Django 4.2.30 on 2026-09-26 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadActorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhishingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_communication_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('webhook_origin', models.CharField(db_index=True, default='Gmail_Phishing_MessageId_Report', max_length=128)),
                ('message_title', models.CharField(blank=True, max_length=500)),
                ('message_body', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reporter_email', models.CharField(blank=True, max_length=254)),
                ('gmail_message_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('rfc822_message_id', models.CharField(blank=True, db_index=True, max_length=512)),
                ('origin_sender', models.CharField(blank=True, db_index=True, max_length=254)),
                ('conversation_key', models.CharField(blank=True, db_index=True, max_length=180)),
                ('rfc822_fetch_status', models.CharField(blank=True, db_index=True, max_length=32)),
                ('reported_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phishing_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='PhishingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_email', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('analyst_verdict', models.CharField(choices=[('unknown', 'unknown'), ('phishing', 'phishing'), ('malware', 'malware'), ('spam', 'spam'), ('legitimate', 'legitimate')], default='unknown', max_length=32)),
                ('analyst_confidence', models.CharField(blank=True, max_length=16)),
                ('analyst_notes', models.TextField(blank=True)),
                ('analyst_verdict_at', models.DateTimeField(blank=True, null=True)),
                ('reporter_ai_guidance_json', models.JSONField(blank=True, default=dict)),
                ('reporter_ai_internal_generated_at', models.DateTimeField(blank=True, null=True)),
                ('reporter_ai_gemini_generated_at', models.DateTimeField(blank=True, null=True)),
                ('reporter_ai_last_request_payload', models.JSONField(blank=True, default=dict)),
                ('analyst_verdict_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phishing_verdicts', to=settings.AUTH_USER_MODEL)),
                ('cluster_canonical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_peers', to='phishing.phishingsubmission')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='phishing.phishingreport')),
            ],
        ),
        migrations.CreateModel(
            name='PhishingExtractedArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(max_length=32)),
                ('role', models.CharField(blank=True, max_length=64)),
                ('value', models.TextField(blank=True)),
                ('lookup_key', models.CharField(max_length=512)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='phishing.phishingsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='PhishingCampaignContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_email', models.CharField(max_length=254)),
                ('vote', models.CharField(max_length=16)),
                ('gmail_message_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='phishing.phishingreport')),
            ],
        ),
        migrations.CreateModel(
            name='IntelScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('provider', models.CharField(max_length=32)),
                ('lookup_key', models.CharField(db_index=True, max_length=512)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intel_scans', to='phishing.phishingsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BadActorReportLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_links', to='phishing.badactorprofile')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_actor_links', to='phishing.phishingreport')),
            ],
        ),
        migrations.CreateModel(
            name='BadActorArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(max_length=32)),
                ('lookup_key', models.CharField(db_index=True, max_length=512)),
                ('value', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='phishing.badactorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gmail_report_api', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phishing_api_clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='phishingsubmission',
            index=models.Index(fields=['risk_score', 'analyst_verdict'], name='phishing_ph_risk_sc_0ba7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='phishingreport',
            index=models.Index(fields=['webhook_origin', '-reported_at'], name='phishing_ph_webhook_f7ddcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='phishingreport',
            constraint=models.UniqueConstraint(condition=models.Q(('gmail_message_id__gt', '')), fields=('webhook_origin', 'gmail_message_id'), name='uniq_phish_gmail_message'),
        ),
        migrations.AddIndex(
            model_name='phishingextractedartifact',
            index=models.Index(fields=['lookup_key'], name='phishing_ph_lookup__d02b40_idx'),
        ),
        migrations.AddConstraint(
            model_name='phishingextractedartifact',
            constraint=models.UniqueConstraint(fields=('submission', 'artifact_type', 'lookup_key'), name='uniq_phish_artifact_lookup'),
        ),
        migrations.AddConstraint(
            model_name='phishingcampaigncontribution',
            constraint=models.UniqueConstraint(fields=('campaign_report', 'reporter_email'), name='uniq_phish_campaign_vote'),
        ),
        migrations.AddConstraint(
            model_name='badactorreportlink',
            constraint=models.UniqueConstraint(fields=('profile', 'report'), name='uniq_bad_actor_report'),
        ),
    ]
